[package]
name = "rust-bench-test"
version = "0.1.0"
authors = ["Matan Kushner <hello@matchai.dev>"]
edition = "2018"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benches"
harness = false
