[package]
name = "rust-bench-test"
version = "0.1.0"
authors = ["Matan Kushner <hello@matchai.dev>"]
edition = "2018"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[lib]
bench = false

[[bench]]
name = "benches"
harness = false
